## K-means for iris

In [54]:
import pandas as pd
import numpy as np

In [83]:
url = 'iris.csv'

newCols = ['Len_1', 'Wid_1','Len_2', 'Wid_2', 'class']
df_org = pd.read_csv(url, header=None, names=newCols)
                    #  第一筆資料 不是 header  
# df_org[70:120]
df_org


Len_1  Wid_1  Len_2  Wid_2           class
0      5.1    3.5    1.4    0.2     Iris-setosa
1      4.9    3.0    1.4    0.2     Iris-setosa
2      4.7    3.2    1.3    0.2     Iris-setosa
3      4.6    3.1    1.5    0.2     Iris-setosa
4      5.0    3.6    1.4    0.2     Iris-setosa
..     ...    ...    ...    ...             ...
145    6.7    3.0    5.2    2.3  Iris-virginica
146    6.3    2.5    5.0    1.9  Iris-virginica
147    6.5    3.0    5.2    2.0  Iris-virginica
148    6.2    3.4    5.4    2.3  Iris-virginica
149    5.9    3.0    5.1    1.8  Iris-virginica

[150 rows x 5 columns]

In [92]:
# 先 將 ['class'] 這欄，做 LabelEncoder 
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()

df_org['class'] = labelencoder.fit_transform(df_org['class'])
df_org


Len_1  Wid_1  Len_2  Wid_2  class
0      5.1    3.5    1.4    0.2      0
1      4.9    3.0    1.4    0.2      0
2      4.7    3.2    1.3    0.2      0
3      4.6    3.1    1.5    0.2      0
4      5.0    3.6    1.4    0.2      0
..     ...    ...    ...    ...    ...
145    6.7    3.0    5.2    2.3      2
146    6.3    2.5    5.0    1.9      2
147    6.5    3.0    5.2    2.0      2
148    6.2    3.4    5.4    2.3      2
149    5.9    3.0    5.1    1.8      2

[150 rows x 5 columns]

### 切出 輸入資料 (df_x) 及 正確答案 (df_y):     


In [93]:
# 正確答案 df_y
df_y =  df_org['class']
df_y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: class, Length: 150, dtype: int64

In [94]:
# 切出 輸入資料
df_x = df_org.iloc[: , 0:4]
df_x

Len_1  Wid_1  Len_2  Wid_2
0      5.1    3.5    1.4    0.2
1      4.9    3.0    1.4    0.2
2      4.7    3.2    1.3    0.2
3      4.6    3.1    1.5    0.2
4      5.0    3.6    1.4    0.2
..     ...    ...    ...    ...
145    6.7    3.0    5.2    2.3
146    6.3    2.5    5.0    1.9
147    6.5    3.0    5.2    2.0
148    6.2    3.4    5.4    2.3
149    5.9    3.0    5.1    1.8

[150 rows x 4 columns]

### 用 training set 作 K mean 分類

In [95]:
from sklearn.cluster import KMeans
# K Means model  (無監督 學習)

km = KMeans(n_clusters=3)
km.fit(df_x)


KMeans(n_clusters=3)

In [96]:
# kmeans 分類結果
#

km.labels_

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 2, 0, 0, 2, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 0, 2, 2, 2, 2,
       2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0])

In [89]:
# 標準答案
#

df_y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: class, Length: 150, dtype: int32

In [91]:
# 檢查共有 多少 bit error
#
myErr = np.array(df_y) - km.labels_
myErr
# sum(abs(myErr))

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,
        0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  1,  1,  0,  0,  0,  0,
        1,  0,  1,  0,  1,  0,  0,  1,  1,  0,  0,  0,  0,  0,  1,  0,  0,
        0,  0,  1,  0,  0,  0,  1,  0,  0,  0,  1,  0,  0,  1])

In [100]:
myErr = np.array(df_ans) - km.labels_
# myErr
# sum(abs(myErr))
lst = list(myErr)
150 - lst.count(0)

16

#### testing....

In [ ]:
# 小技巧 0-->1, 1-->0

dict1 = {0:1, 1:0}
df_ans = df_y
df_ans.replace(dict1, inplace=True)
df_ans

In [19]:
np.array(df_y)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [16]:
# 加入分群結果 # 加上類別

df_x['類別'] = km.labels_
df_x

Len_1  Wid_1  Len_2  Wid_2  類別
0      5.1    3.5    1.4    0.2   1
1      4.9    3.0    1.4    0.2   1
2      4.7    3.2    1.3    0.2   1
3      4.6    3.1    1.5    0.2   1
4      5.0    3.6    1.4    0.2   1
..     ...    ...    ...    ...  ..
145    6.7    3.0    5.2    2.3   2
146    6.3    2.5    5.0    1.9   0
147    6.5    3.0    5.2    2.0   2
148    6.2    3.4    5.4    2.3   2
149    5.9    3.0    5.1    1.8   0

[150 rows x 5 columns]

In [17]:
# 解讀資料
a = df_y - df_x['類別']
np.array(a)

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,
        1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  2,
        0,  0,  0,  0,  2,  0,  0,  0,  0,  0,  0,  2,  2,  0,  0,  0,  0,
        2,  0,  2,  0,  2,  0,  0,  2,  2,  0,  0,  0,  0,  0,  2,  0,  0,
        0,  0,  2,  0,  0,  0,  2,  0,  0,  0,  2,  0,  0,  2])

In [18]:
b = np.array(a)
sum(abs(b))

128

### 針對 其他 分類  
